
ALTER TABLE pronto_orders
ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS waiter_accepted_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS chef_accepted_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS check_requested_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS feedback_requested_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS feedback_completed_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP NULL;
