-- ============================================================================
-- PRONTO SEED: Menu Items
-- ============================================================================
-- Creates menu items with UPSERT logic
-- Run order: 0330 (after categories)
-- ============================================================================

-- Insert or update menu items
INSERT INTO pronto_menu_items (
    id, name, description, price, category_id, image_path,
    preparation_time_minutes, is_breakfast_recommended,
    is_afternoon_recommended, is_night_recommended,
    is_quick_serve, is_available
)
VALUES
    (gen_random_uuid(), 'Combo Familiar', '4 hamburguesas, papas y bebidas.', 29.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Combos'), 'menu/combos_familiar.png', 30, false, true, true, false, true),
    (gen_random_uuid(), 'Combo Pareja', '2 hamburguesas, 2 papas medianas y 2 bebidas.', 18.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Combos'), 'menu/combo_pareja.png', 25, false, false, false, false, true),
    (gen_random_uuid(), 'Combo Individual', '1 hamburguesa, papas pequeñas y bebida.', 10.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Combos'), 'menu/combo_individual.png', 20, false, false, false, false, true),
    (gen_random_uuid(), 'Combo Pizza Grande', 'Pizza grande, papas fritas y 2 bebidas.', 24.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Combos'), 'menu/combo_pizza.png', 28, false, false, false, false, true),
    (gen_random_uuid(), 'Combo Tacos Fiesta', '6 tacos variados, guacamole y 2 bebidas.', 22.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Combos'), 'menu/combo_tacos.png', 25, false, false, false, false, true),
    (gen_random_uuid(), 'Combo Ensalada Saludable', 'Ensalada grande, wrap de pollo y smoothie.', 16.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Combos'), 'menu/combo_ensalada.png', 18, false, false, false, false, true),
    (gen_random_uuid(), 'Hamburguesa Doble Queso', 'Doble carne y queso, pan artesanal.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_doble.png', 18, false, true, false, false, true),
    (gen_random_uuid(), 'Hamburguesa Clásica', 'Carne de res, lechuga, tomate y cebolla.', 7.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_clasica.png', 15, false, false, false, false, true),
    (gen_random_uuid(), 'Hamburguesa BBQ Bacon', 'Carne, bacon, queso cheddar y salsa BBQ.', 10.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_bbq.png', 18, false, false, false, false, true),
    (gen_random_uuid(), 'Hamburguesa Vegetariana', 'Medallón de garbanzos, aguacate y vegetales.', 8.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_veggie.png', 16, false, false, false, false, true),
    (gen_random_uuid(), 'Hamburguesa Mexicana', 'Carne, jalapeños, guacamole y queso pepper jack.', 11.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_mexicana.png', 19, false, false, false, false, true),
    (gen_random_uuid(), 'Hamburguesa de Pollo Crispy', 'Pollo empanizado, lechuga, tomate y mayonesa.', 9.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_pollo.png', 17, false, false, false, false, true),
    (gen_random_uuid(), 'Hamburguesa Blue Cheese', 'Carne angus, queso azul, cebolla caramelizada.', 12.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Hamburguesas'), 'menu/hamburguesa_blue.png', 18, false, false, false, false, true),
    (gen_random_uuid(), 'Pizza Margherita', 'Tomate, mozzarella fresca y albahaca.', 11.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_margherita.png', 22, false, true, true, false, true),
    (gen_random_uuid(), 'Pizza Pepperoni', 'Salsa de tomate, mozzarella y pepperoni.', 13.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_pepperoni.png', 22, false, false, false, false, true),
    (gen_random_uuid(), 'Pizza Cuatro Quesos', 'Mozzarella, gorgonzola, parmesano y provolone.', 14.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_cuatro_quesos.png', 24, false, false, false, false, true),
    (gen_random_uuid(), 'Pizza Hawaiana', 'Jamón, piña y queso mozzarella.', 12.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_hawaiana.png', 22, false, false, false, false, true),
    (gen_random_uuid(), 'Pizza Vegetariana', 'Tomate, champiñones, pimientos, cebolla y aceitunas.', 13.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_vegetariana.png', 23, false, false, false, false, true),
    (gen_random_uuid(), 'Pizza BBQ Chicken', 'Pollo, salsa BBQ, cebolla morada y cilantro.', 14.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_bbq_chicken.png', 24, false, false, false, false, true),
    (gen_random_uuid(), 'Pizza Carnívora', 'Pepperoni, salchicha, jamón y bacon.', 15.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Pizzas'), 'menu/pizza_carnivora.png', 25, false, false, false, false, true),
    (gen_random_uuid(), 'Tacos al Pastor', '3 tacos con carne al pastor, piña y cilantro.', 8.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Tacos'), 'menu/tacos_pastor.png', 12, false, true, true, false, true),
    (gen_random_uuid(), 'Tacos de Carnitas', '3 tacos con carnitas de cerdo y cebolla.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Tacos'), 'menu/tacos_carnitas.png', 13, false, false, false, false, true),
    (gen_random_uuid(), 'Tacos de Pescado', '3 tacos con pescado empanizado y col.', 10.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Tacos'), 'menu/tacos_pescado.png', 14, false, false, false, false, true),
    (gen_random_uuid(), 'Tacos de Pollo', '3 tacos con pollo marinado y aguacate.', 8.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Tacos'), 'menu/tacos_pollo.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Tacos de Camarón', '3 tacos con camarones al ajillo y col.', 12.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Tacos'), 'menu/tacos_camaron.png', 15, false, false, false, false, true),
    (gen_random_uuid(), 'Tacos Veganos', '3 tacos con setas, frijoles y vegetales.', 7.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Tacos'), 'menu/tacos_veganos.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Ensalada César', 'Lechuga romana, pollo, crutones y parmesano.', 8.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Ensaladas'), 'menu/ensalada_cesar.png', 8, true, true, false, false, true),
    (gen_random_uuid(), 'Ensalada Mediterránea', 'Tomate, pepino, aceitunas, queso feta.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Ensaladas'), 'menu/ensalada_mediterranea.png', 10, true, true, false, false, true),
    (gen_random_uuid(), 'Ensalada de Pollo a la Parrilla', 'Pollo, lechuga, tomate cherry, maíz y aguacate.', 10.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Ensaladas'), 'menu/ensalada_pollo.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Ensalada Caprese', 'Tomate, mozzarella fresca, albahaca y balsámico.', 8.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Ensaladas'), 'menu/ensalada_caprese.png', 7, false, false, false, false, true),
    (gen_random_uuid(), 'Ensalada de Quinoa', 'Quinoa, garbanzos, pepino, pimiento y limón.', 9.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Ensaladas'), 'menu/ensalada_quinoa.png', 9, false, false, false, false, true),
    (gen_random_uuid(), 'Coca-Cola', 'Refresco de cola 500ml.', 2.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/coca_cola.png', 2, false, false, false, true, true),
    (gen_random_uuid(), 'Agua Mineral', 'Agua mineral natural 500ml.', 1.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/agua.png', 1, false, false, false, true, true),
    (gen_random_uuid(), 'Jugo de Naranja', 'Jugo natural recién exprimido.', 3.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/jugo_naranja.png', 15, false, false, false, true, true),
    (gen_random_uuid(), 'Limonada Natural', 'Limonada fresca preparada al momento.', 3.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/limonada.png', 15, false, false, false, true, true),
    (gen_random_uuid(), 'Cerveza Artesanal', 'Cerveza local 330ml.', 4.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/cerveza.png', 2, false, false, false, true, true),
    (gen_random_uuid(), 'Café Americano', 'Café negro recién preparado.', 2.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/cafe_americano.png', 4, false, false, false, true, true),
    (gen_random_uuid(), 'Café Latte', 'Espresso con leche vaporizada.', 3.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/cafe_latte.png', 5, true, false, false, true, true),
    (gen_random_uuid(), 'Té Helado', 'Té negro helado con limón 500ml.', 2.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/te_helado.png', 3, false, false, false, true, true),
    (gen_random_uuid(), 'Smoothie de Frutas', 'Batido de frutas tropicales.', 4.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/smoothie.png', 5, true, true, false, true, true),
    (gen_random_uuid(), 'Cerveza Nacional', 'Cerveza nacional 355ml.', 3.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/cerveza_nacional.png', 2, false, false, false, true, true),
    (gen_random_uuid(), 'Agua de Horchata', 'Agua fresca de arroz con canela.', 2.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/agua_horchata.png', 3, false, false, false, true, true),
    (gen_random_uuid(), 'Agua de Jamaica', 'Agua fresca de flor de Jamaica.', 2.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/agua_jamaica.png', 3, false, false, false, true, true),
    (gen_random_uuid(), 'Agua de Tamarindo', 'Agua fresca de tamarindo natural.', 2.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/agua_tamarindo.png', 3, false, false, false, true, true),
    (gen_random_uuid(), 'Malteada de Chocolate', 'Malteada cremosa de chocolate con crema batida.', 5.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/malteada_chocolate.png', 6, false, false, false, true, true),
    (gen_random_uuid(), 'Malteada de Fresa', 'Malteada de fresa con crema batida.', 5.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/malteada_fresa.png', 6, false, false, false, true, true),
    (gen_random_uuid(), 'Malteada de Vainilla', 'Clásica malteada de vainilla con crema.', 5.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/malteada_vainilla.png', 6, false, false, false, true, true),
    (gen_random_uuid(), 'Frappe de Café', 'Café frío batido con hielo y crema.', 5.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/frappe_cafe.png', 5, false, false, false, true, true),
    (gen_random_uuid(), 'Cappuccino', 'Espresso con espuma de leche y canela.', 4.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/cappuccino.png', 5, true, false, false, true, true),
    (gen_random_uuid(), 'Michelada', 'Cerveza preparada con limón, sal y salsas.', 5.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Bebidas'), 'menu/michelada.png', 4, false, false, false, true, true),
    (gen_random_uuid(), 'Cheesecake Frutos Rojos', 'Porción individual con coulis casero.', 4.90, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/cheesecake_rojo.png', 15, false, true, true, false, true),
    (gen_random_uuid(), 'Brownie con Helado', 'Brownie de chocolate con helado de vainilla.', 5.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/brownie_helado.png', 7, false, false, false, false, true),
    (gen_random_uuid(), 'Tiramisú', 'Postre italiano tradicional.', 5.90, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/tiramisu.png', 5, false, false, false, false, true),
    (gen_random_uuid(), 'Helado Artesanal', '3 bolas de helado a elegir.', 4.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/helado.png', 4, false, false, false, false, true),
    (gen_random_uuid(), 'Flan Casero', 'Flan de huevo con caramelo líquido.', 4.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/flan.png', 5, false, false, false, false, true),
    (gen_random_uuid(), 'Pastel de Chocolate', 'Rebanada de pastel de chocolate con ganache.', 5.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/pastel_chocolate.png', 6, false, false, false, false, true),
    (gen_random_uuid(), 'Churros con Chocolate', 'Churros recién hechos con chocolate caliente.', 4.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Postres'), 'menu/churros.png', 8, false, false, false, false, true),
    (gen_random_uuid(), 'Chilaquiles Rojos', 'Tortilla frita bañada en salsa roja, crema y queso.', 8.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/chilaquiles_rojos.png', 15, true, false, false, false, true),
    (gen_random_uuid(), 'Chilaquiles Verdes', 'Tortilla frita bañada en salsa verde con pollo.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/chilaquiles_verdes.png', 15, true, false, false, false, true),
    (gen_random_uuid(), 'Huevos Rancheros', 'Huevos estrellados sobre tortilla con salsa ranchera.', 7.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/huevos_rancheros.png', 12, true, false, false, false, true),
    (gen_random_uuid(), 'Huevos con Jamón', 'Huevos revueltos con jamón, frijoles y tortillas.', 7.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/huevos_jamon.png', 10, true, false, false, false, true),
    (gen_random_uuid(), 'Hotcakes con Miel', 'Stack de 3 hotcakes esponjosos con miel de maple.', 6.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/hotcakes.png', 8, true, false, false, false, true),
    (gen_random_uuid(), 'Molletes', 'Bolillo con frijoles, queso gratinado y pico de gallo.', 6.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/molletes.png', 10, true, false, false, false, true),
    (gen_random_uuid(), 'Omelette', 'Omelette de 3 huevos con queso, jamón y champiñones.', 8.00, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/omelette.png', 12, true, false, false, false, true),
    (gen_random_uuid(), 'Pan Francés', 'Rebanadas de pan con huevo, canela y azúcar glass.', 7.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Desayunos'), 'menu/pan_frances.png', 10, true, false, false, false, true),
    (gen_random_uuid(), 'Alitas BBQ', '10 alitas de pollo con salsa BBQ y aderezo ranch.', 11.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/alitas_bbq.png', 20, false, false, false, false, true),
    (gen_random_uuid(), 'Alitas Buffalo', '10 alitas picantes estilo Buffalo con apio.', 11.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/alitas_buffalo.png', 20, false, false, false, false, true),
    (gen_random_uuid(), 'Nachos Supreme', 'Totopos con queso, carne, guacamole y crema.', 10.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/nachos.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Dedos de Queso', '8 dedos de mozzarella empanizados con marinara.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/dedos_queso.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Aros de Cebolla', 'Aros de cebolla empanizados con salsa ranch.', 7.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/aros_cebolla.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Papas con Queso y Tocino', 'Papas fritas cubiertas con queso cheddar y tocino.', 8.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/papas_queso_tocino.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Guacamole con Totopos', 'Guacamole fresco preparado al momento con totopos.', 7.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/guacamole.png', 8, false, false, false, false, true),
    (gen_random_uuid(), 'Camarones al Coco', '8 camarones empanizados con coco y salsa agridulce.', 13.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Botanas'), 'menu/camarones_coco.png', 15, false, false, false, false, true),
    (gen_random_uuid(), 'Quesadillas de Pollo', 'Tortilla de harina con queso y pollo deshebrado.', 8.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/quesadilla_pollo.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Quesadillas de Champiñones', 'Tortilla con queso Oaxaca y champiñones.', 7.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/quesadilla_champinones.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Torta Cubana', 'Torta con jamón, salchicha, huevo, queso y aguacate.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/torta_cubana.png', 15, false, false, false, false, true),
    (gen_random_uuid(), 'Torta de Milanesa', 'Milanesa de pollo o res con frijoles y aguacate.', 8.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/torta_milanesa.png', 14, false, false, false, false, true),
    (gen_random_uuid(), 'Sopes', '3 sopes con frijoles, carne, lechuga y crema.', 9.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/sopes.png', 16, false, false, false, false, true),
    (gen_random_uuid(), 'Flautas', '4 flautas de pollo con crema, queso y guacamole.', 9.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/flautas.png', 14, false, false, false, false, true),
    (gen_random_uuid(), 'Enchiladas Verdes', '3 enchiladas bañadas en salsa verde con pollo.', 10.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/enchiladas_verdes.png', 18, false, false, false, false, true),
    (gen_random_uuid(), 'Enchiladas Rojas', '3 enchiladas en salsa roja con queso y crema.', 10.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/enchiladas_rojas.png', 18, false, false, false, false, true),
    (gen_random_uuid(), 'Gorditas', '2 gorditas rellenas de chicharrón, queso o frijoles.', 8.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Antojitos Mexicanos'), 'menu/gorditas.png', 15, false, false, false, false, true),
    (gen_random_uuid(), 'Sopa de Tortilla', 'Sopa de tomate con tiras de tortilla, aguacate y queso.', 7.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Sopas'), 'menu/sopa_tortilla.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Crema de Champiñones', 'Cremosa sopa de champiñones con crutones.', 7.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Sopas'), 'menu/crema_champinones.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Consomé de Pollo', 'Caldo de pollo con verduras y arroz.', 6.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Sopas'), 'menu/consome_pollo.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Minestrone', 'Sopa italiana de vegetales y pasta.', 7.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Sopas'), 'menu/minestrone.png', 12, false, false, false, false, true),
    (gen_random_uuid(), 'Crema de Tomate', 'Suave crema de tomate con albahaca.', 6.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Sopas'), 'menu/crema_tomate.png', 10, false, false, false, false, true),
    (gen_random_uuid(), 'Arrachera', '300g de arrachera a la parrilla con guarnición.', 18.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/arrachera.png', 25, false, false, true, false, true),
    (gen_random_uuid(), 'Filete de Pescado', 'Filete de pescado al mojo de ajo con arroz y verduras.', 16.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/filete_pescado.png', 20, false, false, false, false, true),
    (gen_random_uuid(), 'Pollo a la Parrilla', 'Pechuga de pollo marinada con papas y ensalada.', 14.50, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/pollo_parrilla_1769982743280.png', 22, false, false, false, false, true),
    (gen_random_uuid(), 'Fajitas Mixtas', 'Pollo y carne con pimientos, cebolla y tortillas.', 17.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/fajitas_mixtas.png', 20, false, false, true, false, true),
    (gen_random_uuid(), 'Camarones al Ajillo', 'Camarones salteados en aceite de oliva y ajo.', 19.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/camarones_ajillo.png', 18, false, false, false, false, true),
    (gen_random_uuid(), 'Molcajete', 'Carne asada, pollo, camarones y chorizo en molcajete.', 24.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/molcajete.png', 30, false, false, true, false, true),
    (gen_random_uuid(), 'Costillas BBQ', 'Costillas de cerdo bañadas en salsa BBQ.', 21.99, (SELECT id FROM pronto_menu_categories WHERE name = 'Especialidades'), 'menu/costillas_bbq.png', 35, false, false, true, false, true);

-- Note: ON CONFLICT not used because name is not unique across categories
-- This is a one-time seed, not an upsert